//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licensing.Repository.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivationLog
    {
        public long ActivationLogId { get; set; }
        public string ActivationInfo { get; set; }
        public System.DateTime Timestamp { get; set; }
    }
}
