//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licensing.Repository.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComputerClient
    {
        public int ComputerClientId { get; set; }
        public int LicensePeriodId { get; set; }
        public string HardwareId { get; set; }
        public string ClientHost { get; set; }
        public bool IsObsolete { get; set; }
        public Nullable<System.DateTime> TimestampActivation { get; set; }
    
        public virtual LicensePeriod LicensePeriod { get; set; }
    }
}
