//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licensing.Repository.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class License
    {
        public License()
        {
            this.LicensePeriod = new HashSet<LicensePeriod>();
        }
    
        public int LicenseId { get; set; }
        public string Name { get; set; }
        public int ClientId { get; set; }
        public string ActivationCode { get; set; }
        public string LicenseCode { get; set; }
        public bool IsActive { get; set; }
        public bool IsObsolete { get; set; }
        public System.DateTime InsDateTime { get; set; }
        public string InsUserId { get; set; }
        public Nullable<System.DateTime> UpdDateTime { get; set; }
        public string UpdUserId { get; set; }
        public Nullable<System.DateTime> DelDateTime { get; set; }
        public string DelUserId { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
        public virtual AspNetUsers AspNetUsers2 { get; set; }
        public virtual Client Client { get; set; }
        public virtual ICollection<LicensePeriod> LicensePeriod { get; set; }
    }
}
