//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licensing.Repository.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewLicenseGrid
    {
        public int LicenseId { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
        public bool IsObsolete { get; set; }
        public System.DateTime InsDateTime { get; set; }
        public string InsUserName { get; set; }
        public int ClientId { get; set; }
    }
}
